---
title: "HW1"
author: "Kunyu An"
date: "2/12/2021"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
library(tidyverse)
library(viridis)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```


```{r load_libraries}
library(ISLR)
```

### Problem 5

we want to show that $\hat{y}_{i} = \sum_{i'=1}^n a_{i'}y_{i'}$. Given that $\hat{\beta} = (\sum_{i=1}^n x_{i}y_{i})/(\sum_{i'=1}^n x_{i'}^2) $, we have


<center>$\hat{y}_{i} = x_{i}\hat{\beta} = x_{i}\frac{\sum_{i=1}^n x_{i}y_{i}}{\sum_{i'=1}^n x_{i'}^2} = \frac{x_{i}}{\sum_{i'=1}^n x_{i'}^2}\sum_{i=1}^n x_{i}y_{i}$</center>

Since $\frac{x_{i}}{\sum_{i'=1}^n x_{i'}^2}$ is a constant for any i', we can represent it as a constant $C_{i'}$. Then we get,

<center>$\hat{y}_{i} = C_{i'}\sum_{i=1}^n x_{i}y_{i} = \sum_{i=1}^n C_{i'}x_{i}y_{i}$</center>

Let $a_{i'} = C_{i'}x_{i}$, we get,

<center>$\hat{y}_{i} = \sum_{i=1}^n C_{i'}x_{i}y_{i} =  \sum_{i'=1}^n a_{i'}y_{i'}$</center>
